---
dovecot_service_name: dovecot

dovecot_packages:
  - dovecot-imapd
  - dovecot-lmtpd
  - mutt

dovecot_protocols:
  - imap
  - lmtp

dovecot_default_process_limit: 10
dovecot_default_client_limit: 100

dovecot_mail_location: "maildir:~/Maildir"
dovecot_mail_privileged_group: mail
dovecot_mail_plugins:

dovecot_root_namespace_type: private
dovecot_root_namespace_separator: /
dovecot_root_namespace_prefix:
dovecot_root_namespace_hidden: "no"
dovecot_root_namespace_inbox: "yes"

dovecot_auth_mechanisms: plain login cram-md5
dovecot_disable_plaintext_auth: "no"

dovecot_auth_debug: "no"

dovecot_service_imaplogin_imap_port: 0
dovecot_service_imaplogin_imap_ssl: "no"
dovecot_service_imaplogin_imaps_port: 993
dovecot_service_imaplogin_imaps_ssl: "yes"

dovecot_service_imap_process_limit: 10

dovecot_service_authworker_user: "$default_internal_user"

dovecot_service_auth_unix_listener: /var/spool/postfix/private/auth
dovecot_service_auth_unix_listener_user: postfix
dovecot_service_auth_unix_listener_group: postfix
dovecot_service_auth_unix_listener_mode: "0660"
dovecot_service_auth_user: "$default_internal_user"

dovecot_service_lmtp_unix_listener: /var/spool/postfix/private/dovecot-lmtp
dovecot_service_lmtp_unix_listener_user: postfix
dovecot_service_lmtp_unix_listener_group: postfix
dovecot_service_lmtp_unix_listener_mode: "0660"

dovecot_protocol_imap_mail_plugins: "$mail_plugins mail_log notify"

dovecot_protocol_lmtp_postmaster_address: "postmaster@{{ hostname_fqdn }}"

dovecot_log_path:
dovecot_info_log_path:
dovecot_mail_debug: "no"
dovecot_syslog_facility: local1

dovecot_ssl: required
dovecot_ssl_cert: "</etc/ssl/certs/ssl-cert-snakeoil.pem"
dovecot_ssl_key: "</etc/ssl/private/ssl-cert-snakeoil.key"

dovecot_passdb_driver: passwd-file
dovecot_passdb_args: scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users
dovecot_passdb_master: "no"
dovecot_passdb_pass: "no"
dovecot_passdb_skip: never

dovecot_userdb_driver: passwd-file
dovecot_userdb_args: username_format=%u /etc/dovecot/users
dovecot_userdb_default_fields: uid=vmail gid=vmail home=/home/vmail/%u

# Though we do not authenticate using system users so the username lookup will
# fail against the passwd-file we also know we should not expect any user with
# these system names to even try and login, this extra layer hopefully prevents
# some accidents due to configuration mistakes.
# getent passwd | awk -F':' '{print $1}' | sort
dovecot_deny_users:
  - _apt
  - _chrony
  - backup
  - bin
  - bind
  - daemon
  - dovecot
  - dovenull
  - gnats
  - iodine
  - landscape
  - mail
  - man
  - messagebus
  - nobody
  - postfix
  - proxy
  - root
  - sshd
  - sync
  - sys
  - syslog
  - systemd-bus-proxy
  - systemd-network
  - systemd-resolve
  - systemd-timesync
  - uuidd
  - vmail
  - www-data

# Example users format to populate /etc/dovecot/users file
# dovecot_users:
#  - username: foobar@example.com
#    password: "{SHA512-CRYPT}$6$0G4lQx4ZbodhFLlH$AmuAx23Puy14iv2.S5qOAAXg/xG9GtTQs42ctnRnQWOke5dP2QXwEw9WplALZn3Za985HlRUR18fo"
#    uid: 999
#    gid: 998
#    home: /var/mail/virtual/example.com/foobar
