---
minecraft_gamemode: creative
minecraft_server_jar_url: https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar
minecraft_motd: i like cats
minecraft_difficulty: peaceful
minecraft_spawn_monsters: "true"
