---
- name: Manage user toby
  ansible.builtin.import_tasks: toby.yml

- name: Remove unnecessary users
  ansible.builtin.import_tasks: remove_users.yml

- name: Handle vagrant users
  ansible.builtin.import_tasks: vagrant.yml
