---
- name: Ensure unnecessary users are absent
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ users_to_remove + additional_users_to_remove | default([], true) }}"
