---
# ~ id
# uid=20003(toby) gid=100(users) groups=100(users),4(adm),27(sudo),999(sshlogin)
# ~ getent passwd toby
# toby:x:20003:100:Toby Oxborrow <toby@oxborrow.net>:/home/toby:/bin/bash

- name: Ensure user toby exists
  ansible.builtin.user:
    name: toby
    comment: Toby Oxborrow <toby@oxborrow.net>
    group: users
    groups: adm,sudo,sshlogin
    shell: /bin/bash
    createhome: true
    state: present
    system: false

- name: Ensure home directory directory permissions
  ansible.builtin.file:
    path: /home/toby
    mode: 0700

- name: Ensure authorized_keys file is present
  ansible.builtin.authorized_key:
    user: toby
    key: https://github.com/tobyoxborrow.keys
    exclusive: true
    state: present
    manage_dir: true

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/tobyoxborrow/dotfiles
    remote: origin
    version: HEAD  # noqa git-latest
    clone: true
    update: false
    dest: /home/toby/.dotfiles
  become: true
  become_user: toby
  register: clone_dotfiles
  notify: Run dotfiles script
