---
# ~ id
# uid=20003(toby) gid=100(users) groups=100(users),4(adm),27(sudo),999(sshlogin)
# ~ getent passwd toby
# toby:x:20003:100:Toby Oxborrow <toby@oxborrow.net>:/home/toby:/bin/bash

- name: Ensure user toby exists
  user:
    name: toby
    comment: Toby Oxborrow <toby@oxborrow.net>
    group: users
    groups: adm,sudo,sshlogin
    shell: /bin/bash
    createhome: yes
    state: present
    system: no

- name: Ensure home directory directory permissions
  file:
    path: /home/toby
    mode: 0700

- name: Ensure authorized_keys file is present
  authorized_key:
    user: toby
    key: https://github.com/tobyoxborrow.keys
    exclusive: yes
    state: present
    manage_dir: yes

- name: Ensure git is installed
  package:
    name: git
    state: present

- name: Clone dotfiles
  git:
    repo: https://github.com/tobyoxborrow/dotfiles
    remote: origin
    version: HEAD
    clone: yes
    update: no
    dest: /home/toby/.dotfiles
  become: yes
  become_user: toby
  register: clone_dotfiles

- name: Run dotfiles script
  command: /home/toby/.dotfiles/dotfiles.sh
  become: yes
  become_user: toby
  register: dotfiles_sh
  changed_when: dotfiles_sh.stdout != ""
  when: clone_dotfiles is changed
