---
- name: Ensure user ubuntu is a member of sshlogin group on vagrant
  ansible.builtin.user:
    name: "ubuntu"
    groups: adm,sudo,sshlogin
  when: vagrant

- name: Ensure user ubuntu is absent when not on vagrant
  ansible.builtin.user:
    name: "ubuntu"
    state: absent
  when: not vagrant
