---
- name: Stat letsencrypt certs
  stat:
    path: "/etc/letsencrypt/live/{{ item.domain }}/fullchain.pem"
  with_items: "{{ letsencrypt_certs }}"
  register: stat_certs
  changed_when: no

- name: Initialise missing certs
  command: "{{ item.item.command }}"
  with_items: "{{ stat_certs.results }}"
  when: "{{ not item.stat.exists }}"
