---
- name: Ensure letsencrypt cronjob script is present
  template:
    src: templates/letsencrypt-renewal.j2
    dest: /usr/local/bin/letsencrypt-renewal
    owner: root
    group: root
    mode: 0755

- name: Ensure letsencrypt cronjob is present
  cron:
    name: "letsencrypt renewal"
    job: "/usr/local/bin/letsencrypt-renewal"
    state: present
    hour: "0"
    minute: "0"
