---
- name: Ensure letsencrypt cronjob script is present
  ansible.builtin.template:
    src: templates/letsencrypt-renewal.j2
    dest: /usr/local/bin/letsencrypt-renewal
    owner: root
    group: root
    mode: 0755

- name: Ensure letsencrypt cronjob job is present
  ansible.builtin.cron:
    name: "letsencrypt renewal"
    job: "/usr/local/bin/letsencrypt-renewal"
    special_time: daily
    cron_file: letsencrypt-renewal
    user: root
    state: present
