---
- name: Manage letsencrypt package
  ansible.builtin.import_tasks: package.yml

- name: Manage letsencrypt cronjobs
  ansible.builtin.import_tasks: cronjobs.yml
  when: not development and not vagrant

- name: Manage letsencrypt certs
  ansible.builtin.import_tasks: certs.yml
  when: not development and not vagrant
