repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.2.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      additional_dependencies: [ansible]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.15.1
  hooks:
    - id: gitlint
