---
- name: Ensure motd is present
  ansible.builtin.template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Ensure motd.tail is present
  ansible.builtin.template:
    src: templates/motd.tail.j2
    dest: /etc/motd.tail
    owner: root
    group: root
    mode: 0644

- name: Synchronize update-motd.d files
  ansible.builtin.copy:
    src: files/update-motd.d/
    dest: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755

- name: Synchronize recent script files
  ansible.builtin.copy:
    src: files/cron.daily/
    dest: /etc/cron.daily/
    owner: root
    group: root
    mode: 0755
  when: motd_install_recent_scripts

- name: Verify recent scripts are installed
  ansible.builtin.command: run-parts --test /etc/cron.daily
  register: runparts
  failed_when: runparts.stdout.find('/etc/cron.daily/recent_') == -1
  changed_when: false
  when: motd_install_recent_scripts

- name: Verify 10-help-text exists
  ansible.builtin.stat:
    path: /etc/update-motd.d/10-help-text
  register: helptext
  changed_when: false
  check_mode: true

- name: Ensure 10-help-text is not executable
  ansible.builtin.file:
    path: /etc/update-motd.d/10-help-text
    mode: 0644
  when: helptext.stat.exists

- name: Verify 51-cloudguest exists
  ansible.builtin.stat:
    path: /etc/update-motd.d/51-cloudguest
  register: cloudguest
  changed_when: false
  check_mode: true

- name: Ensure 51-cloudguest is not executable
  ansible.builtin.file:
    path: /etc/update-motd.d/51-cloudguest
    mode: 0644
  when: cloudguest.stat.exists

- name: Ensure /etc/issue is present
  ansible.builtin.template:
    src: templates/etc-issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: Ensure /etc/issue.net is present
  ansible.builtin.template:
    src: templates/etc-issue-net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
