---
- name: Ensure motd.tail is present
  template:
    dest: /etc/motd.tail
    src: templates/motd.tail.j2
    owner: root
    group: root
    mode: 0644

- name: Synchronize update-motd.d files
  copy:
    src: files/update-motd.d/
    dest: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755

- name: Synchronize recent script files
  copy:
    src: files/cron.daily/
    dest: /etc/cron.daily/
    owner: root
    group: root
    mode: 0755

- name: Ensure help-text is not executable
  file:
    path: /etc/update-motd.d/10-help-text
    mode: 0644

- name: Verify 51-cloudguest exists
  stat:
    path: "/etc/update-motd.d/51-cloudguest"
  register: cloudguest
  changed_when: false
  check_mode: yes

- name: Ensure 51-cloudguest is not executable
  file:
    path: /etc/update-motd.d/51-cloudguest
    mode: 0644
  when: cloudguest.stat.exists
