---
# Based on the steps here:
# https://help.ui.com/hc/en-us/articles/220066768-UniFi-How-to-Install-and-Update-via-APT-on-Debian-or-Ubuntu

- name: Ensure openjdk-11 is not selectable
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - openjdk-11-jdk
    - openjdk-11-jdk-headless
    - openjdk-11-jre
    - openjdk-11-jre-zero

- name: Ensure ca-certificates is installed
  ansible.builtin.package:
    name: ca-certificates
    state: present

- name: Ensure apt-transport-https is installed
  ansible.builtin.package:
    name: apt-transport-https
    state: present

- name: Ensure unifi apt key is present
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50
    state: present

- name: Ensure sources.list.d/100-ubnt-unifi.list is present
  ansible.builtin.copy:
    src: files/etc-apt-sources.list.d.100-ubnt-unifi.list
    dest: /etc/apt/sources.list.d/100-ubnt-unifi.list
    owner: root
    group: root
    mode: 0644

- name: Ensure mongodb apt key is present
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.4.asc
    state: present

- name: Ensure sources.list.d/mongodb-org-3.4.list is present
  ansible.builtin.copy:
    src: files/etc-apt-sources.list.d-mongodb-org-3.4.list
    dest: /etc/apt/sources.list.d/mongodb-org-3.4.list
    owner: root
    group: root
    mode: 0644

- name: Ensure unifi is installed
  ansible.builtin.package:
    name: unifi
    state: present
