---
- name: postmap generic
  ansible.builtin.command: postmap /etc/postfix/generic

- name: postmap vmailbox
  ansible.builtin.command: postmap /etc/postfix/vmailbox

- name: postmap virtual
  ansible.builtin.command: postmap /etc/postfix/virtual

- name: postmap recipient_bcc_maps
  ansible.builtin.command: postmap /etc/postfix/recipient_bcc_maps

- name: postmap access
  ansible.builtin.command: postmap /etc/postfix/access

- name: postmap client_whitelist
  ansible.builtin.command: postmap /etc/postfix/client_whitelist

- name: postmap denied_recipients
  ansible.builtin.command: postmap /etc/postfix/denied_recipients

- name: postmap sender_logins
  ansible.builtin.command: postmap /etc/postfix/sender_logins

- name: postmap static files
  ansible.builtin.command: >
    postmap
    /etc/postfix/header_checks
    /etc/postfix/helo_access
    /etc/postfix/localdomains
    /etc/postfix/relay_domains
    /etc/postfix/transport

- name: reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
