---
- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: postmap generic
  command: postmap /etc/postfix/generic

- name: postmap virtual
  command: postmap /etc/postfix/virtual

- name: postmap access
  command: postmap /etc/postfix/access

- name: postmap client_whitelist
  command: postmap /etc/postfix/client_whitelist

- name: postmap denied_recipients
  command: postmap /etc/postfix/denied_recipients

- name: postmap static files
  command: postmap /etc/postfix/header_checks /etc/postfix/helo_access /etc/postfix/localdomains /etc/postfix/relay_domains /etc/postfix/transport
