---
- name: Postmap generic
  ansible.builtin.command: postmap /etc/postfix/generic

- name: Postmap vmailbox
  ansible.builtin.command: postmap /etc/postfix/vmailbox

- name: Postmap virtual
  ansible.builtin.command: postmap /etc/postfix/virtual

- name: Postmap header_checks
  ansible.builtin.command: postmap /etc/postfix/header_checks

- name: Postmap recipient_bcc_maps
  ansible.builtin.command: postmap /etc/postfix/recipient_bcc_maps

- name: Postmap access
  ansible.builtin.command: postmap /etc/postfix/access

- name: Postmap client_whitelist
  ansible.builtin.command: postmap /etc/postfix/client_whitelist

- name: Postmap denied_recipients
  ansible.builtin.command: postmap /etc/postfix/denied_recipients

- name: Postmap sender_logins
  ansible.builtin.command: postmap /etc/postfix/sender_logins

- name: Postmap static files
  ansible.builtin.command: >
    postmap
    /etc/postfix/helo_access
    /etc/postfix/localdomains
    /etc/postfix/relay_domains
    /etc/postfix/transport

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
