---
hostname: dvd
hostname_fqdn: "{{ hostname }}.home.oxborrow.net"

sshd_banner_filename: "banner_{{ hostname }}.txt"

# public_inet_address: n/a

firewall_tcp_ports:
  - "{{ sshd_config_port }}"
  - 8080

fail2ban_enable_nginx: no
fail2ban_enable_postfix: no
fail2ban_enable_dovecot: no

# letsencrypt_certs:
#   - domain: "{{ hostname_fqdn }}"
#     command: letsencrypt certonly --webroot -w /var/www/html -m toby@oxborrow.net -d www.oxborrow.net --agree-tos

hardening_disable_filesystems:
- cramfs
- freevxfs
- jffs2
- hfs
- hfsplus
- squashfs
- udf
# - vfat  # raspberry pi uses vfat for boot partition

base_packages_to_remove:
  # - avahi-daemon  # dependancy of OSMC
  # - nano  # dependancy of OSMC
  # - nfs-common  # dependancy of OSMC
  - cups  # CIS Ensure CUPS is not enabled
  - eatmydata
  - emacsen-common
  - iamerican
  - laptop-detect
  - ldap-utils  # CIS Ensure LDAP client is not enabled
  - nis  # CIS Ensure NIS Server is not enabled
  - openbsd-inetd  # CIS Ensure openbsd-inetd is not installed
  - rsh-client  # CIS Ensure rsh client is not enabled
  - samba  # CIS Ensure Samba is not enabled
  - slapd  # CIS Ensure LDAP server is not enabled
  - snmpd  # CIS Ensure SNMP Server is not enabled
  - talk  # CIS Ensure talk client is not enabled
  - telnet  # CIS Ensure telnet client is not enabled
  - vsftpd  # CIS Ensure FTP Server is not enabled
  - wamerican
  - xauth
  - xinetd  # CIS Ensure xinetd is not installed
  - xserver-xorg*  # CIS Ensure X Window System is not installed
