---
hostname: halifax
hostname_fqdn: "{{ hostname }}.oxborrow.net"
sshd_banner_filename: "banner_{{ hostname }}.txt"
public_inet_address: 209.141.56.246
sshd_config_port: 63822
firewall_tcp_ports:
  - "{{ sshd_config_port }}"
  - 80
  - 25
fail2ban_enable_nginx: yes
fail2ban_enable_postfix: yes
