---
hostname: pihole

firewall_tcp_ports:
  - "{{ sshd_config_port }}"
  - 80
  - 53
  - 443
  - 8080
  - 8443

remove_base_packages: true
remove_cis_packages: true
remove_desktop_packages: true

hardening_disable_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - squashfs
  - udf
  # - vfat  # raspberry pi uses vfat for boot partition
