---
hostname: wellington
hostname_fqdn: "{{ hostname }}.oxborrow.net"

sshd_banner_filename: "banner_{{ hostname }}.txt"

public_inet_address: 104.244.76.123

firewall_tcp_ports:
  - "{{ sshd_config_port }}"
  - 80
  - 25
  - 993
  - 587

fail2ban_enable_nginx: true
fail2ban_enable_postfix: true

letsencrypt_certs:
  - domain: wellington.oxborrow.net
    command: letsencrypt certonly --webroot -w /var/www/html -m toby@oxborrow.net -d wellington.oxborrow.net --agree-tos

postfix_smtpd_tls_cert_file: /etc/letsencrypt/live/wellington.oxborrow.net/fullchain.pem
postfix_smtpd_tls_key_file: /etc/letsencrypt/live/wellington.oxborrow.net/privkey.pem
