---
- name: Ensure hostname is set
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Ensure hostname with local address is in /etc/hosts
  ansible.builtin.lineinfile:
    line: "127.0.0.1 {{ hostname_fqdn }} {{ hostname }} localhost.localdomain localhost"
    regexp: '^127.0.0.1\s'
    dest: /etc/hosts
    state: present
  when: public_inet_address is not defined

- name: Ensure localhost with local address is in /etc/hosts
  ansible.builtin.lineinfile:
    line: "127.0.0.1 localhost.localdomain localhost"
    regexp: '^127.0.0.1\s'
    dest: /etc/hosts
    state: present
  when: public_inet_address is defined

- name: Ensure hostname with public address is in /etc/hosts
  ansible.builtin.lineinfile:
    line: "{{ public_inet_address }} {{ hostname_fqdn }} {{ hostname }}"
    regexp: "^{{ public_inet_address }} "
    dest: /etc/hosts
    state: present
  when: public_inet_address is defined
