---
- name: Ensure chrony.conf is present
  ansible.builtin.template:
    dest: /etc/chrony/chrony.conf
    src: templates/chrony.conf.j2
    owner: root
    group: root
    mode: 0644
  notify: Restart chrony
