---
- name: Manage alternative ntp packages
  include: ntp.yml
  when: chrony_enable_role

- name: Manage chrony package
  include: package.yml
  when: chrony_enable_role

- name: Manage chrony configuration
  include: configuration.yml
  when: chrony_enable_role
