---
- name: Manage alternative ntp packages
  ansible.builtin.import_tasks: ntp.yml
  when: chrony_enable_role

- name: Manage chrony package
  ansible.builtin.import_tasks: package.yml
  when: chrony_enable_role

- name: Manage chrony configuration
  ansible.builtin.import_tasks: configuration.yml
  when: chrony_enable_role
