---
- name: Manage alternative ntp packages
  import_tasks: ntp.yml
  when: chrony_enable_role

- name: Manage chrony package
  import_tasks: package.yml
  when: chrony_enable_role

- name: Manage chrony configuration
  import_tasks: configuration.yml
  when: chrony_enable_role
