---
- name: Ensure chrony is installed
  ansible.builtin.package:
    name: chrony
    state: present

- name: Ensure service started and enabled
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
