---
postfix_master_smtp_inet: true
postfix_master_submission_inet: false
postfix_smtpd_banner: ESMTP
postfix_mydomain: localhost
postfix_myhostname: localhost
postfix_mydestination: $myhostname localhost.$mydomain localhost
postfix_myorigin: $myhostname
postfix_inet_interfaces: 127.0.0.1
postfix_inet_protocols: ipv4
postfix_smtpd_recipient_restrictions:
  - check_client_access hash:/etc/postfix/client_whitelist
  - check_recipient_access hash:/etc/postfix/denied_recipients
  - reject_unknown_sender_domain
  - reject_unknown_recipient_domain
postfix_smtpd_sender_restrictions:
  - permit_mynetworks
postfix_smtpd_relay_restrictions:
  - permit_mynetworks
  - permit_sasl_authenticated
  - reject_unauth_destination
# postfix_virtual_mailbox_domains: example.com
postfix_virtual_mailbox_base: /var/mail/virtual
# postfix_virtual_default_entry: example.com
postfix_virtual_minimum_uid: 900
# postfix_virtual_uid_maps: static:999
# postfix_virtual_gid_maps: static:998
postfix_virtual_entries:
  - pattern: foo@example.com
    value: bar@example.com
postfix_virtual_mailbox_entries:
  - address: foo@example.com
    mailbox: example.com/foo/
postfix_generic_entries:
  - pattern: "@localhost.localdomain"
    value: no-reply@localhost.localdomain
postfix_client_whitelist:
  - example.com
postfix_access_entries:
  - pattern: "trogdor@example.com"
    value: "500 Burninated!"
postfix_denied_recipients:
  - strongbad@localhost
postfix_sender_login_entries:
  - username: foo@example.com
    address: foo@example.com

postfix_smtpd_sasl_auth_enable: "no"

postfix_smtpd_tls_ask_ccert: "no"
postfix_smtpd_tls_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
postfix_smtpd_tls_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
postfix_smtpd_tls_loglevel: 1
postfix_smtpd_tls_received_header: "yes"
postfix_smtpd_tls_security_level: "may"
