---
base_packages_to_remove:
  - eatmydata
  - nano
  - xauth
  - wamerican

# instead of redefining the above, you can just populate the following list
additional_base_packages_to_remove:

base_packages_to_install:
  - bsd-mailx
  - git-core
  - man-db
  - ncat
  - nmap
  - tmux

# instead of redefining the above, you can just populate the following list
additional_base_packages_to_install:
