---
- name: Ensure configuration file jail.d/defaults-debian.conf is absent
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    state: absent
  notify: reload fail2ban

- name: Ensure configuration file jail.d/sshd.conf is present
  ansible.builtin.template:
    src: templates/jails.d-sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: 0644
  notify: reload fail2ban

- name: Ensure configuration file jail.d/nginx.conf is present
  ansible.builtin.template:
    src: templates/jails.d-nginx.conf.j2
    dest: /etc/fail2ban/jail.d/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload fail2ban

- name: Ensure configuration file jail.d/postfix.conf is present
  ansible.builtin.template:
    src: templates/jails.d-postfix.conf.j2
    dest: /etc/fail2ban/jail.d/postfix.conf
    owner: root
    group: root
    mode: 0644
  notify: reload fail2ban
