---
- name: Manage sshd package
  ansible.builtin.import_tasks: package.yml

- name: Configure sshd package
  ansible.builtin.import_tasks: sshd_config.yml

- name: Manage sshd service
  ansible.builtin.import_tasks: service.yml
