---
# this seems unlikely not to be the case if Ansible is working at all
# included for completeness
- name: Ensure openssh-server is installed
  package:
    name: "{{ sshd_package_name }}"
    state: present

- name: Ensure service started and enabled
  service:
    name: "{{ sshd_service_name }}"
    state: started
    enabled: yes
