---
- name: Reload systemctl daemon
  systemd:
    daemon_reload: true
  notify: Enable minecraft server service

- name: Enable minecraft server service
  ansible.builtin.service:
    name: "minecraft@{{ minecraft_gamemode }}.service"
    enabled: true
  notify: Start minecraft server service

- name: Start minecraft server service
  ansible.builtin.service:
    name: "minecraft@{{ minecraft_gamemode }}.service"
    state: started
