---
- name: Ensure certain base services are disabled
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ base_services_to_disable + additional_base_services_to_disable | default([], true) }}"

- name: Ensure certain base packages are absent
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ base_packages_to_remove + additional_base_packages_to_remove | default([], true) }}"
  notify: apt-get autoremove

- name: Ensure certain base packages are present
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages_to_install + additional_base_packages_to_install | default([], true) }}"
