---
- name: Ensure certain base packages are absent
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ base_packages_to_remove + additional_base_packages_to_remove | default([], true) }}"
  notify: apt-get autoremove

- name: Ensure certain base packages are present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages_to_install + additional_base_packages_to_install | default([], true) }}"
