---
- name: 4.1.1.1 Ensure auditd is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - auditd
    - audispd-plugins

- name: 4.1.1.2 Ensure auditd service is enabled
  ansible.builtin.service:
    name: auditd
    enabled: true

- name: Stat /boot/grub/grub.cfg
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: stat_boot_grub_grub_cfg
  changed_when: false

- name: 4.1.1.3 Ensure auditd grub config
  ansible.builtin.lineinfile:
    dest: /etc/defaults/grub
    insertafter: EOF
    state: present
    regexp: ^GRUB_CMDLINE_LINUX.*audit=1.*audit_backlog_limit=8192
    line: 'GRUB_CMDLINE_LINUX="audit=1 audit_backlog_limit=8192"'
    create: true
    owner: root
    group: root
    mode: 0644
  notify: Update grub
  when: stat_boot_grub_grub_cfg.stat.exists

- name: 4.1.2.1 Ensure audit log storage size is configured
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    insertafter: EOF
    state: present
    regexp: ^max_log_file\s*=
    line: "max_log_file = 128"

- name: 4.1.2.2 Ensure audit logs are not automatically deleted
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    insertafter: EOF
    state: present
    regexp: ^max_log_file_action\s*=
    line: "max_log_file_action = keep_logs"

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (space_left_action)
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    insertafter: EOF
    state: present
    regexp: ^space_left_action\s*=
    line: "space_left_action = email"

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (action_mail_acct)
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    insertafter: EOF
    state: present
    regexp: ^action_mail_acct\s*=
    line: "action_mail_acct = root"

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (admin_space_left_action)
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    insertafter: EOF
    state: present
    regexp: ^admin_space_left_action\s*=
    line: "admin_space_left_action = email"

- name: 4.1 Ensure various events are collected
  ansible.builtin.copy:
    src: files/audit-rules-CIS.rules
    dest: /etc/audit/rules.d/CIS.rules
    owner: root
    group: root
    mode: 0644
