---
- name: 1.1 Filesystem Configuration
  include: filesystems.yml

- name: 1.3 Sudo
  include: sudo.yml

- name: 1.5 Secure Boot Settings
  include: boot.yml

- name: 1.6 Additional Process Hardening
  include: process.yml

- name: 1.9 Software Updates Installed
  include: software_updates.yml

- name: 3.2 Network Parameters (Host Only)
  include: network_parameters_host.yml

- name: 3.3 Network Parameters (Host and Router)
  include: network_parameters_hostrouter.yml

- name: 3.4 Uncommon Network Protocols
  include: network_protocols.yml

- name: 3.5 Firewall Configuration
  include: iptables.yml

- name: 4.1 Configure System Accounting (auditd)
  include: auditd.yml
