---
- name: 1.1 Filesystem Configuration
  ansible.builtin.import_tasks: filesystems.yml

- name: 1.3 Sudo
  ansible.builtin.import_tasks: sudo.yml

- name: 1.5 Secure Boot Settings
  ansible.builtin.import_tasks: boot.yml

- name: 1.6 Additional Process Hardening
  ansible.builtin.import_tasks: process.yml

- name: 1.9 Software Updates Installed
  ansible.builtin.import_tasks: software_updates.yml

- name: 3.2 Network Parameters (Host Only)
  ansible.builtin.import_tasks: network_parameters_host.yml

- name: 3.3 Network Parameters (Host and Router)
  ansible.builtin.import_tasks: network_parameters_hostrouter.yml

- name: 3.4 Uncommon Network Protocols
  ansible.builtin.import_tasks: network_protocols.yml

- name: 3.5 Firewall Configuration
  ansible.builtin.import_tasks: iptables.yml

- name: 4.1 Configure System Accounting (auditd)
  ansible.builtin.import_tasks: auditd.yml
