---
- name: 3.3.1 Ensure source routed packets are not accepted
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv6.conf.default.accept_source_route

- name: 3.3.2 Ensure ICMP redirects are not accepted
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects

- name: 3.3.3 Ensure secure ICMP redirects are not accepted
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: 3.3.4 Ensure suspicious packets are logged
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians

- name: 3.3.5 Ensure broadcast ICMP requests are ignored
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
  notify: Flush routing cache

- name: 3.3.6 Ensure bogus ICMP responses are ignored
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
  notify: Flush routing cache

- name: 3.3.7 Ensure Reverse Path Filtering is enabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter

- name: 3.3.8 Ensure TCP SYN Cookies is enabled
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
  notify: Flush routing cache

- name: 3.3.9 Ensure IPv6 router advertisements are not accepted
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
