---
- name: 3.1.1 Ensure IP forwarding is disabled
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
  notify: flush routing cache

- name: 3.1.2 Ensure packet redirect sending is disabled
  sysctl:
    name: "{{ item }}"
    value: 0
  notify: flush routing cache
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
