---
- name: 3.2.1 Ensure packet redirect sending is disabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects

- name: 3.2.2 Ensure IP forwarding is disabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
  notify: Flush routing cache
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
