---
- name: 1.5.1 Ensure core dumps are restricted (limits)
  lineinfile:
    dest: /etc/security/limits.d/core.conf
    insertafter: EOF
    state: present
    regexp: ^\*\s+hard\s+core
    line: "* hard core 0"
    create: yes
    owner: root
    group: root
    mode: 0644

- name: 1.5.1 Ensure core dumps are restricted (sysctl)
  sysctl:
    name: fs.suid_dumpable
    value: 0

- name: 1.5.3 Ensure address space layout randomization is enabled
  sysctl:
    name: kernel.randomize_va_space
    value: 2

- name: 1.5.4 Stat prelink
  command: "dpkg -s prelink"
  register: dpkg_prelink
  ignore_errors: true
  changed_when: false

- name: 1.5.4 Restore prelink binaries to normal
  command: "prelink -ua"
  when: dpkg_prelink|succeeded

- name: 1.5.4 Ensure prelink is absent
  package:
    name: prelink
    state: absent
  when: dpkg_prelink|succeeded
