---
- name: 1.6.2 Ensure address space layout randomization is enabled
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: 2

- name: 1.6.3 Stat prelink
  ansible.builtin.command: "dpkg -s prelink"
  register: dpkg
  ignore_errors: true
  changed_when: false
  failed_when: "'Status: install ok installed' not in dpkg.stdout"
  no_log: true

- name: 1.6.3 Restore prelink binaries to normal
  ansible.builtin.command: "prelink -ua"
  when: dpkg is succeeded

- name: 1.6.3 Ensure prelink is absent
  ansible.builtin.package:
    name: prelink
    state: absent
  when: dpkg is succeeded

- name: 1.6.4 Ensure core dumps are restricted (limits)
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.d/core.conf
    insertafter: EOF
    state: present
    regexp: ^\*\s+hard\s+core
    line: "* hard core 0"
    create: true
    owner: root
    group: root
    mode: 0644

- name: 1.6.4 Ensure core dumps are restricted (sysctl)
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: 0
