---
- name: 1.9 Ensure unattended-upgrades is installed
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: 1.9 Ensure unattended-upgrades is configured (50unattended-upgrades)
  ansible.builtin.template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: 1.9 Ensure unattended-upgrades is configured (20auto-upgrades)
  ansible.builtin.template:
    src: templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: 1.9 Ensure unattended-upgrades service is enabled
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
