---
- name: 1.3.2 Ensure sudo commands use pty
  ansible.builtin.copy:
    src: sudoers.d-10-CIS-defaults-pty
    dest: /etc/sudoers.d/10-CIS-defaults-pty
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/visudo -cf %s

- name: 1.3.3 Ensure sudo log file exists
  ansible.builtin.copy:
    src: sudoers.d-10-CIS-defaults-logfile
    dest: /etc/sudoers.d/10-CIS-defaults-logfile
    owner: root
    group: adm
    mode: 0640
    validate: /usr/sbin/visudo -cf %s
