---
logwatch_mail_to: root
logwatch_mail_from: "logwatch@{{ hostname_fqdn }}"

logwatch_services:
  - All
  - -cron
  - -eximstats
  - -http
  - -postfix
  - -sendmail
  - -zz-disk_space
  - -zz-network
  - -zz-sys

# Set cronjob and range
# cadence of "daily" or "weekly"
logwatch_cadence: "weekly"
