---
- name: Ensure server.properties is present
  ansible.builtin.template:
    dest: "/opt/minecraft/{{ minecraft_gamemode }}/server.properties"
    src: templates/server.properties.j2
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0600
    backup: true

- name: Ensure rcon.conf is present
  ansible.builtin.template:
    dest: "/opt/minecraft/{{ minecraft_gamemode }}/rcon.conf"
    src: templates/rcon.conf.j2
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0600
    backup: true

- name: Ensure ops.json is present
  ansible.builtin.template:
    dest: "/opt/minecraft/{{ minecraft_gamemode }}/ops.json"
    src: templates/ops.json.j2
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0600
    backup: true