---
- name: Ensure rcon package is installed
  ansible.builtin.package:
    name: rcon
    state: present

- name: Ensure minecraft gamemode directory exists
  ansible.builtin.file:
    path: "{{ minecraft_home }}/{{ minecraft_gamemode }}"
    mode: 0755
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory

- name: Ensure log directory exists
  ansible.builtin.file:
    path: "/var/log/minecraft/{{ minecraft_gamemode }}"
    mode: 0775
    owner: root
    group: "{{ minecraft_group }}"
    state: directory

- name: Ensure symlink to log directory exists
  ansible.builtin.file:
    src: "/var/log/minecraft/{{ minecraft_gamemode }}"
    dest: "{{ minecraft_home }}/{{ minecraft_gamemode }}/logs"
    state: link

- name: Ensure minecraft backups directory exists
  ansible.builtin.file:
    path: "/var/backups/minecraft/"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Ensure minecraft server.jar is present
  ansible.builtin.get_url:
    url: "{{ minecraft_server_jar_url }}"
    dest: "{{ minecraft_home }}/{{ minecraft_gamemode }}/server.jar"
    mode: 0644
    owner: root
    group: root
    force: false
