---
- name: Ensure minecraft-start script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-start.j2
    dest: /usr/local/bin/minecraft-start
    owner: root
    group: root
    mode: 0755

- name: Ensure minecraft-stop script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-stop.j2
    dest: /usr/local/bin/minecraft-stop
    owner: root
    group: root
    mode: 0755

- name: Ensure /etc/systemd/system/minecraft@.service is present
  ansible.builtin.template:
    src: templates/etc-systemd-system.minecraft.service.j2
    dest: /etc/systemd/system/minecraft@.service
    owner: root
    group: root
    mode: 0644
  no_log: true
  notify: Reload systemctl daemon
