---
- name: Ensure minecraft-server script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-server.j2
    dest: /usr/local/bin/minecraft-server
    owner: root
    group: minecraft
    mode: 0754

- name: Ensure minecraft-server-stop script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-server-stop.j2
    dest: /usr/local/bin/minecraft-server-stop
    owner: root
    group: minecraft
    mode: 0754

- name: Ensure minecraft-server-backup script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-server-backup.j2
    dest: /usr/local/bin/minecraft-server-backup
    owner: root
    group: root
    mode: 0744

# Debian runs the daily cron job at 06:25 (see /etc/crontab)
- name: Ensure minecraft-server-backup cronjob is present
  ansible.builtin.cron:
    name: "minecraft server backup"
    job: "/usr/local/bin/minecraft-server-backup"
    special_time: daily
    cron_file: minecraft-server-backup
    user: root
    state: present

- name: Ensure /etc/systemd/system/minecraft@.service is present
  ansible.builtin.template:
    src: templates/etc-systemd-system.minecraft.service.j2
    dest: /etc/systemd/system/minecraft@.service
    owner: root
    group: root
    mode: 0644
  no_log: true
  notify: Reload systemctl daemon

- name: Ensure the message script is present
  ansible.builtin.template:
    src: templates/usr-local-bin-minecraft-server-say.j2
    dest: /usr/local/bin/minecraft-server-say
    owner: root
    group: root
    mode: 0744

- name: Ensure any message cronjobs are present
  ansible.builtin.cron:
    name: "minecraft server message {{ item.name }}"
    job: "/usr/local/bin/minecraft-server-say \"{{ item.message }}\""
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    cron_file: "minecraft-server-message-{{ item.file_name }}"
    user: root
    state: present
  with_items: "{{ minecraft_cron_messages | default([], true) }}"
