---
- name: Ensure logrotate is installed
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Ensure configuration file logrotate.conf is present
  ansible.builtin.template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644
