---
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx-light
    state: present

- name: Ensure service started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
