---
- name: Ensure default nginx site is present
  ansible.builtin.template:
    src: templates/site.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

- name: Ensure default index file is removed
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
