---
- name: home.oxborrow.net
  hosts:
    - pihole
    - dvd
    - minecraft
  become: true
  become_user: root
  roles:
    - base_packages
    - hostname
    - motd
    - chrony
    - sshd_group
    - users
    - sshd
    - pam
    - logrotate
    - hardening
    - fail2ban
    # - logwatch

- name: pihole.home.oxborrow.net
  hosts:
    - pihole
  become: true
  become_user: root
  roles:
    - unifi

- name: minecraft.home.oxborrow.net
  hosts:
    - minecraft
  become: true
  become_user: root
  roles:
    - minecraft
