---
- name: oxborrow.net mailservers
  hosts: [halifax, wellington]
  become: yes
  become_user: root
  roles:
    - base_packages
    - hostname
    - sshd_group
    - users
    - sshd
    - chrony
    - motd
    - logrotate
    - hardening
    - fail2ban
    - logwatch
    - role: letsencrypt
      tags: mail
    - role: postfix
      tags: mail
    - role: dovecot
      tags: mail
    - nginx
    - varwww
