---
- name: wellington.oxborrow.net
  hosts: wellington
  become: yes
  become_user: root
  roles:
    - base_packages
    - hostname
    - motd
    - chrony
    - sshd_group
    - users
    - sshd
    - pam
    - logrotate
    - hardening
    - fail2ban
    - logwatch
    - role: letsencrypt
      tags: mail
    - role: postfix
    tags: mail
    - role: dovecot
    tags: mail
    - nginx
    - varwww

- name: wintermute.oxborrow.net
  hosts: wintermute
  become: yes
  become_user: root
  roles:
    - base_packages
    - hostname
    - motd
    - chrony
    - sshd_group
    - users
    - sshd
    - pam

- name: freeside.oxborrow.net
  hosts: freeside
  become: yes
  become_user: root
  roles:
    - base_packages
    - hostname
    - motd
    - chrony
    - sshd_group
    - users
    - sshd
    - pam
