---
- name: www.oxborrow.net
  hosts:
    - freeside
    - wellington
    - wintermute
  become: true
  become_user: root
  roles:
    - base_packages
    - hostname
    - motd
    - chrony
    - sshd_group
    - users
    - sshd
    - pam
    - logrotate
    - hardening
    - fail2ban
    - logwatch
    - letsencrypt
    - postfix
    # - dovecot
    - nginx
    - varwww
