---
- name: Ensure git bare directory exists
  ansible.builtin.file:
    path: /srv/www.oxborrow.net
    state: directory
    owner: root
    group: root
    mode: 0755

# we clone to a local git bare repo of the website content
# it is purposefully stored outside of the docroot to ensure there are no git
# bits in the docroot
# we also do not pollute a git work tree with any temporary files that may be
# made publicly accessible
# only tracked files will be overwritten in the docroot
- name: Clone www.oxborrow.net
  ansible.builtin.git:
    repo: https://github.com/tobyoxborrow/www.oxborrow.net
    remote: origin
    version: HEAD  # noqa git-latest
    clone: true
    update: false
    dest: /srv/www.oxborrow.net
    bare: true
  notify: Extract git bare to docroot
